name = "RepDays"
uuid = "2d9c6ccd-6cf3-4bd7-92e8-16bde75cd06b"
authors = ["Peter Volkmar <peter.volkmar@energy2020.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
